---
title: "Brian Muir's resume"
author: Brian Muir
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: 
      - override.css         # OVERIDE CERTAIN FUNCTIONS OF CSS
      - resume               # DEFAULT FILE
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> brian.m.muir@gmail.com
- <i class="fa fa-github"></i> [github.com/bmuir](https://github.com/bmuir)
- <i class="fa fa-phone"></i> +1 774-222-2081

Skills {data-icon=suitcase}
--------------------------------------------------------------------------------
Experienced in predictive analytics, statistical analysis, hypothesis testing, exploratory data analysis, experimental design, healthcare analytics, financial forecasting and budgeting.

**Languages and Tools**

- R, SQL, Git / Gitlab, JupyterHub, Excel, Tableau, PowerBI, CSS, Python, C++

**End-to-End R Skills**

- ***Extraction*** (DBI, dbplyr), ***Wrangling*** (dplyr), ***Modeling / Statistics*** (tidymodels, lme4, ts, etc.), ***Visualization*** (ggplot2, plotly, gt, DT, etc.), ***Production*** (RShiny, RMarkdown, RNotebooks, RSConnect)

**Statistics**

- Generalized linear models, time series, regression and classification trees, multi-level (mixed) models, experimental design (ANOVAs, non-parametric methods), lifetime value

Main
================================================================================

Brian Muir, PhD {#title}
--------------------------------------------------------------------------------

Highly-inquisitive team-leader with 11+ years of experience employing machine learning and statistics in the healthcare industry and in computational biology. Direct the forecasting of $billions in pharmacy and medical expenses using predictive models in R for Centene Corporation's (Fortune 500) marketplace insurance LOB.

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Director - Marketplace Forecasting
Centene Corporation / *Actuarial Services*

Chicago, IL

Current - May 2020

### Manager - Analytics & Reporting
Centene Corporation / *Actuarial Services*

Chicago, IL

May 2020 - Jul 2018

- Direct the development, implementation, and presentation of a highly-visible forecast for 7,000+ financial estimates of medical cost and utilization by month for 27 state health plans and 11 claim categories (e.g. hospital inpatient, primary care, specialty Rx).
- Transformed the medical forecast beyond its essential function as a financial reporting tool by adding member-segmented granularity that pinpoints emerging trends for targeted business actions. Present insights to Centene's CFO in monthly calls. 
- Lead a team of six actuaries and data analysts providing regular guidance and skill training sessions in R. 
- Demonstrated ability to build strong collaborations with various technical and non-technical business partners with analytic support and business knowledge across medical, pharmacy, provider, membership, health status, sales, and payment data. 
- Proven record of quickly adapting team workflow to incorporate forecast estimates for direct and indirect COVID costs and various health care policy changes that impacted membership makeup and anticipated costs. 
- Developed a member-level gross margin database that integrates disparate revenue and expense financial data with 40 targeted member, provider, and broker characteristics. Deployed a drill-down dashboard in RSConnect utilized widely for strategic decision making and business initiatives across departments.
- Identified an $8M annual initiative improving on risk adjustment code capture by data-mining pharmacy prior authorization data.


### Data Scientist I

Centene Corporation / *Business Optimization*

Chicago, IL

Jul 2018 - Oct 2017

### Data Analyst II

Centene Corporation / *Business Optimization*

Chicago, IL

Oct 2017 - Sep 2016

- Built and implemented a novel claims completion model using regression to estimate incurred-but-not-reported expenses prior to month end. Model is used for early-warning and to accelerate preparation of financial reporting and commentary. 
- Developed a probability-based outlier detection model for episodes of care that is used to highlight targets for quality and cost-saving initiatives.
- Designed enterprise's primary care auto-assignment algorithm to optimally assign members to local providers identified as high-quality and low-cost.
- Devised interactive RMarkdown reports using automated commentary to highlight emerging trends in Rx utilization. Present findings monthly to Pharmacy Directors of local health plans. 

Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Graduate Research Assistant / Computational Biology

University of California Riverside

Riverside, CA

Sep 2010 - Aug 2016

- Analyzed large gene expression datasets with R (Bioconductor) using non-parametric statistical models.
- Performed statistical tests of codon evolution in cancer gene-sequence alignments using maximum likelihood models.
- Designed and directed a multi-year longitudinal experimental evolution study on fruit flies that employed advanced experimental design statistics. Supervised two to six undergraduate volunteer research assistants per quarter.
- Taught 18 quarters of upper and lower division biology courses with up to 150 students per week. 
- Mentor of five fellow graduate students in Graduate Student Mentorship Program. 

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### University of California Riverside

Ph.D. in Evolution, Ecology & Organismal Biology

Riverside, CA

2016 - 2010

### Boston College

B.S. in Biology, Psychology (Double Major)

Chestnut Hill, MA

2010 - 2006

Publications and Presentations {data-icon=file}
--------------------------------------------------------------------------------

### The expression of tumour suppressors and proto-oncogenes in tissues susceptible to their hereditary cancers.

**Muir, B.** & Nunney, L. British journal of cancer, 113(2), 345-353.

N/A

2015

### Peto's paradox and the hallmarks of cancer: constructing an evolutionary framework for understanding the incidence of cancer.

Nunney, L. & **Muir, B.** Phil. Trans. R. Soc. B, 370(1673), 20150161.

N/A

2015

### Presentations
International Scientific Conferences

N/A

2014-2015

- International Biannual Evolution and Cancer Conference - Lightning Talk & Poster | 2015
- Evolution Conference - Talk | 2014

Exams & Awards {data-icon=medal}
--------------------------------------------------------------------------------

### Exams
Society of Actuaries

N/A

2018-

- PA - Predictive Analytics | Jun 2019
- SRM - Statistics for Risk Modeling | Jan 2019
- P - Probability | Sep 2018

### Awards
Research and Education

N/A

2010-2016

- GAANN Fellowship | U.S. Department of Education | 2016
- Outstanding Teaching Assistant | UCR Graduate Division | 2015
- Dissertation Year Fellowship Award | UCR | 2015
- Chancellor's Distinguished Fellowship Award | UCR | 2010

